package com.revature.constants;

public enum SuperiorActions {

    NEED_APPROVAL,
    APPROVED,
    AUTO_APPROVED,
    NEED_INFO_FROM_EMPLOYEE,
    NEED_INFO_FROM_DIRECT_SUPERVISOR,
    NEED_INFO_FROM_DEPARTMENT_HEAD,
    REJECTED,
    CHANGE_AMOUNT,
    APPROVE_GRADE,
    REJECT_GRADE,
    APPROVE_PRESENTATION,
    REJECT_PRESENTATION,

    CANCEL,
    ADD_GRADE,
    ADD_EVENT_ATTACHMENTS


}
